apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pgel
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pgel
    app.kubernetes.io/part-of: test
  name: devfile-sample-pgel
  namespace: majackso-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-pgel
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-pgel
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:cca998a3a825923973ee9e351acaa83f8072bdea04f97dfb360d125dfa4300cb
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3001
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
